version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UIver}
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POSTver}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENTver}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
 back_net:
  ipam:
   config:
   - subnet: 10.0.2.0/24
 front_net:
  ipam:
   config:
   - subnet: 10.0.1.0/24
